### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by ifelsedeveloper** [vaclav-zeman/dashboard-react-template#1]
Hello,
We liked the structure of your project but on start it throws the error.

`ath.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at dirname (path.js:1345:5)
    at fileExistsWithCaseSync (/Users/vfadeev/Documents/dashboard-template/node_modules/eslint-plugin-import/lib/core/resolve.js:57:31)
    at relative (/Users/vfadeev/Documents/dashboard-template/node_modules/eslint-plugin-import/lib/core/resolve.js:154:39)
    at resolve (/Users/vfadeev/Documents/dashboard-template/node_modules/eslint-plugin-import/lib/core/resolve.js:197:10)
    at Function.get (/Users/vfadeev/Documents/dashboard-template/node_modules/eslint-plugin-import/lib/core/getExports.js:71:38)
    at processBodyStatement (/Users/vfadeev/Documents/dashboard-template/node_modules/eslint-plugin-import/lib/rules/namespace.js:42:44)
    at Array.forEach (native)
    at EventEmitter.Program (/Users/vfadeev/Documents/dashboard-template/node_modules/eslint-plugin-import/lib/rules/namespace.js:84:12)
    at emitOne (events.js:120:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
`
Could you please help us with start?

npm --version
5.3.0
node --version
v8.2.1

**Comment by codetony25** [comment]
Lower your node version to a more stable version like 6 or 7 as version 8 may have experimental features that may be causing conflicts in your dependencies.

**Comment by lokiiarora** [comment]
I am experiencing the same issues I have a node version of v6.5.0.
![screen shot 2017-10-24 at 7 27 06 pm](https://user-images.githubusercontent.com/20043762/31947230-6daabad0-b8f1-11e7-9b08-4b57b5c13605.png)

**Comment by Dardir** [comment]
I have the same problem too

**Comment by HarishKalepu** [comment]
![image](https://user-images.githubusercontent.com/22928184/35820769-a9f4646e-0acc-11e8-8a0d-5b1ef78af50e.png)

With this versions also facing same issue

**Comment by sureshkodur** [comment]
Me also having the same issue??
